#!/bin/sh
# /usr/bin/lumenpass wrapper.
# The Flutter Linux bundle requires its own working directory so libraries
# in /opt/lumenpass/lib are loaded with the embedded RPATH and Flutter can
# locate its data/flutter_assets next to the binary.
set -e
exec /opt/lumenpass/lumenpass "$@"
